// <auto-generated />
using System;
using BookCatalog.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookCatalog.DAL.EF.Migrations
{
    [DbContext(typeof(BookCatalogDbContext))]
    [Migration("20230921140537_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookCatalog.Domain.Entities.BookAggregate.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PageCount");

                    b.HasIndex("PublicationDate");

                    b.HasIndex("Title");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("71392f48-b247-4001-b306-ba75ba8f1d26"),
                            Description = "Description for Book 0",
                            PageCount = 0,
                            PublicationDate = new DateTime(2023, 9, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 0"
                        },
                        new
                        {
                            Id = new Guid("9b1197b0-30f4-4d55-aafa-da6cb807ef6f"),
                            Description = "Description for Book 1",
                            PageCount = 10,
                            PublicationDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = new Guid("6a6d2934-1f49-4f70-b2cf-124d4d8ed34d"),
                            Description = "Description for Book 2",
                            PageCount = 20,
                            PublicationDate = new DateTime(2023, 9, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 2"
                        },
                        new
                        {
                            Id = new Guid("729af3ef-82e8-4095-a357-f2770feefe75"),
                            Description = "Description for Book 3",
                            PageCount = 30,
                            PublicationDate = new DateTime(2023, 9, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 3"
                        },
                        new
                        {
                            Id = new Guid("00f3f660-08fd-41c1-b7a2-951b63696458"),
                            Description = "Description for Book 4",
                            PageCount = 40,
                            PublicationDate = new DateTime(2023, 9, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 4"
                        },
                        new
                        {
                            Id = new Guid("14b29c2f-cb24-432a-8edc-d45a4bdce3b6"),
                            Description = "Description for Book 5",
                            PageCount = 5,
                            PublicationDate = new DateTime(2023, 9, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = new Guid("f460bd0c-7a3d-448e-a4d3-1658abab5435"),
                            Description = "Description for Book 6",
                            PageCount = 60,
                            PublicationDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 6"
                        },
                        new
                        {
                            Id = new Guid("db4051d0-8c03-4bd9-ba4c-c371d2087c50"),
                            Description = "Description for Book 7",
                            PageCount = 70,
                            PublicationDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 7"
                        },
                        new
                        {
                            Id = new Guid("7a27d6b4-c68d-4a37-a437-744639a3fcb9"),
                            Description = "Description for Book 8",
                            PageCount = 80,
                            PublicationDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 8"
                        },
                        new
                        {
                            Id = new Guid("51c657d6-99da-4a4c-8926-db81db19190b"),
                            Description = "Description for Book 9",
                            PageCount = 90,
                            PublicationDate = new DateTime(2023, 9, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 9"
                        },
                        new
                        {
                            Id = new Guid("dc7ccfc1-3a54-4ee7-b4de-56c23aa52ffd"),
                            Description = "Description for Book 10",
                            PageCount = 10,
                            PublicationDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 10"
                        },
                        new
                        {
                            Id = new Guid("85e701b0-eaa1-4c99-969c-670869961c1f"),
                            Description = "Description for Book 11",
                            PageCount = 110,
                            PublicationDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 11"
                        },
                        new
                        {
                            Id = new Guid("0384694d-1bf7-4315-a6ed-e403edabc7ed"),
                            Description = "Description for Book 12",
                            PageCount = 120,
                            PublicationDate = new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 12"
                        },
                        new
                        {
                            Id = new Guid("0da409b0-e062-462a-a170-6fa8907077eb"),
                            Description = "Description for Book 13",
                            PageCount = 130,
                            PublicationDate = new DateTime(2023, 9, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 13"
                        },
                        new
                        {
                            Id = new Guid("5015bb03-f71d-4721-a4f5-c76867bf2561"),
                            Description = "Description for Book 14",
                            PageCount = 140,
                            PublicationDate = new DateTime(2023, 9, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 14"
                        },
                        new
                        {
                            Id = new Guid("ac1b3f14-4f96-4e6f-a6b7-e3591f459273"),
                            Description = "Description for Book 15",
                            PageCount = 15,
                            PublicationDate = new DateTime(2023, 8, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 15"
                        },
                        new
                        {
                            Id = new Guid("c55a0781-5dd4-496d-933d-770896f54875"),
                            Description = "Description for Book 16",
                            PageCount = 160,
                            PublicationDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 16"
                        },
                        new
                        {
                            Id = new Guid("e01a21c3-8b2c-48f3-80cb-b1be0b6b5ece"),
                            Description = "Description for Book 17",
                            PageCount = 170,
                            PublicationDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 17"
                        },
                        new
                        {
                            Id = new Guid("2cd410e9-6ab1-4217-871c-dcdb01a84b83"),
                            Description = "Description for Book 18",
                            PageCount = 180,
                            PublicationDate = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 18"
                        },
                        new
                        {
                            Id = new Guid("95dab451-30e9-4e34-9922-c888ce2e2b35"),
                            Description = "Description for Book 19",
                            PageCount = 190,
                            PublicationDate = new DateTime(2023, 9, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 19"
                        },
                        new
                        {
                            Id = new Guid("57679eba-bcfa-42c0-9ebb-b92191f66080"),
                            Description = "Description for Book 20",
                            PageCount = 20,
                            PublicationDate = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 20"
                        },
                        new
                        {
                            Id = new Guid("44fdbe9a-cd44-49cd-941a-d311bba9dd2e"),
                            Description = "Description for Book 21",
                            PageCount = 210,
                            PublicationDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 21"
                        },
                        new
                        {
                            Id = new Guid("3040ddc4-5f16-40ed-9d69-125e249b7a4e"),
                            Description = "Description for Book 22",
                            PageCount = 220,
                            PublicationDate = new DateTime(2023, 8, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 22"
                        },
                        new
                        {
                            Id = new Guid("a8044022-6f30-47b0-9574-daeb79c3c851"),
                            Description = "Description for Book 23",
                            PageCount = 230,
                            PublicationDate = new DateTime(2023, 8, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 23"
                        },
                        new
                        {
                            Id = new Guid("9e9829c7-a27a-445d-9164-a517fe9b8dff"),
                            Description = "Description for Book 24",
                            PageCount = 240,
                            PublicationDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 24"
                        },
                        new
                        {
                            Id = new Guid("d8022eaa-e83c-45b1-9e18-11fadb1ce37f"),
                            Description = "Description for Book 25",
                            PageCount = 25,
                            PublicationDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 25"
                        },
                        new
                        {
                            Id = new Guid("e9523829-b0e6-49da-8a63-4839886fee2a"),
                            Description = "Description for Book 26",
                            PageCount = 260,
                            PublicationDate = new DateTime(2023, 8, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 26"
                        },
                        new
                        {
                            Id = new Guid("ce752470-7a99-4592-8307-e6ffd8bc6508"),
                            Description = "Description for Book 27",
                            PageCount = 270,
                            PublicationDate = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 27"
                        },
                        new
                        {
                            Id = new Guid("0636ccf7-87f5-46c6-93d2-abe1caad5daf"),
                            Description = "Description for Book 28",
                            PageCount = 280,
                            PublicationDate = new DateTime(2023, 8, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 28"
                        },
                        new
                        {
                            Id = new Guid("b63b912b-fbb9-4ed0-a143-016ca2ca17d4"),
                            Description = "Description for Book 29",
                            PageCount = 290,
                            PublicationDate = new DateTime(2023, 8, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 29"
                        },
                        new
                        {
                            Id = new Guid("a3d91e02-9b94-46d5-a7ba-dcf18d273001"),
                            Description = "Description for Book 30",
                            PageCount = 30,
                            PublicationDate = new DateTime(2023, 7, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 30"
                        },
                        new
                        {
                            Id = new Guid("d425148d-f9db-4066-9b8e-cc6db298af88"),
                            Description = "Description for Book 31",
                            PageCount = 310,
                            PublicationDate = new DateTime(2023, 8, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 31"
                        },
                        new
                        {
                            Id = new Guid("823d1635-24be-41f2-8102-e536890778f3"),
                            Description = "Description for Book 32",
                            PageCount = 320,
                            PublicationDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 32"
                        },
                        new
                        {
                            Id = new Guid("628b5235-5fbd-4f41-a881-eece17e79cf7"),
                            Description = "Description for Book 33",
                            PageCount = 330,
                            PublicationDate = new DateTime(2023, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 33"
                        },
                        new
                        {
                            Id = new Guid("8f1e3639-f548-47fd-9f1b-8d2fe0360556"),
                            Description = "Description for Book 34",
                            PageCount = 340,
                            PublicationDate = new DateTime(2023, 8, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 34"
                        },
                        new
                        {
                            Id = new Guid("fb924469-5d47-47b1-8d69-e3a3a36fffcf"),
                            Description = "Description for Book 35",
                            PageCount = 35,
                            PublicationDate = new DateTime(2023, 7, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 35"
                        },
                        new
                        {
                            Id = new Guid("85c85e80-7006-4767-b8f4-fb404a8a3420"),
                            Description = "Description for Book 36",
                            PageCount = 360,
                            PublicationDate = new DateTime(2023, 8, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 36"
                        },
                        new
                        {
                            Id = new Guid("80eda9f1-dd17-423a-9913-628a6fa890e7"),
                            Description = "Description for Book 37",
                            PageCount = 370,
                            PublicationDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 37"
                        },
                        new
                        {
                            Id = new Guid("83ea80d2-55bf-49be-bb2f-9f1d73358e61"),
                            Description = "Description for Book 38",
                            PageCount = 380,
                            PublicationDate = new DateTime(2023, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 38"
                        },
                        new
                        {
                            Id = new Guid("b3c47cc9-0a0e-4f1f-a9e0-80fc1269926e"),
                            Description = "Description for Book 39",
                            PageCount = 390,
                            PublicationDate = new DateTime(2023, 8, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 39"
                        },
                        new
                        {
                            Id = new Guid("cf85653b-b46b-41ac-a819-441b1a9c6707"),
                            Description = "Description for Book 40",
                            PageCount = 40,
                            PublicationDate = new DateTime(2023, 7, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 40"
                        },
                        new
                        {
                            Id = new Guid("99e32b98-5b8a-45dd-9231-d811c4a299f9"),
                            Description = "Description for Book 41",
                            PageCount = 410,
                            PublicationDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 41"
                        },
                        new
                        {
                            Id = new Guid("a5977c02-4041-4976-b206-7eb393856361"),
                            Description = "Description for Book 42",
                            PageCount = 420,
                            PublicationDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 42"
                        },
                        new
                        {
                            Id = new Guid("d570c707-f6ea-4b4c-b6b5-69623b76e250"),
                            Description = "Description for Book 43",
                            PageCount = 430,
                            PublicationDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 43"
                        },
                        new
                        {
                            Id = new Guid("a9501a80-aec5-438f-b2c8-b438abf60acd"),
                            Description = "Description for Book 44",
                            PageCount = 440,
                            PublicationDate = new DateTime(2023, 8, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 44"
                        },
                        new
                        {
                            Id = new Guid("e673d23f-de31-43d8-81f5-1fb74ad50351"),
                            Description = "Description for Book 45",
                            PageCount = 45,
                            PublicationDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 45"
                        },
                        new
                        {
                            Id = new Guid("4b06e75f-bd08-4dab-aacb-4a4c3fa9443e"),
                            Description = "Description for Book 46",
                            PageCount = 460,
                            PublicationDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 46"
                        },
                        new
                        {
                            Id = new Guid("68f9fa12-f3ad-4d07-8301-607f42bc80af"),
                            Description = "Description for Book 47",
                            PageCount = 470,
                            PublicationDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 47"
                        },
                        new
                        {
                            Id = new Guid("46fd9d2d-5701-45ff-82cf-ab54725201dc"),
                            Description = "Description for Book 48",
                            PageCount = 480,
                            PublicationDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 48"
                        },
                        new
                        {
                            Id = new Guid("40aaca33-54ae-4dc9-bf2e-5023865003ba"),
                            Description = "Description for Book 49",
                            PageCount = 490,
                            PublicationDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Book 49"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
